ponder_poll/polls/urls.py
from django.urls import path

from polls import views
from polls.views import (
    PollCreateView,
    PollDeleteView,
    PollDetailView,
    PollListView,
    PollUpdateView,
)

urlpatterns = [
    path("", PollListView.as_view(), name="index"),
    path("poll/<int:pk>", PollDetailView.as_view(), name="poll-view"),
    path("poll/add", PollCreateView.as_view(), name="poll-add"),
    path("poll/edit/<int:pk>", PollUpdateView.as_view(), name="poll-edit"),
    path("poll/delete/<int:pk>", PollDeleteView.as_view(), name="poll-delete"),
    path("option/<int:pk>/vote", views.vote_option, name="option-vote"),
]

ponder_poll/ponder_poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("", include(("polls.urls", "polls"), namespace="polls")),
]

ponder_poll/polls/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Count

User = get_user_model()


class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-id",)

    def __str__(self):
        return self.text

    @property
    def total_votes(self):
        votes = Poll.objects.filter(pk=self.pk).aggregate(
            total=Count("options__votes")
        )
        return votes["total"]


class Option(models.Model):
    poll = models.ForeignKey(
        Poll, on_delete=models.CASCADE, related_name="options"
    )
    text = models.CharField(max_length=200)

    class Meta:
        ordering = ("-id",)
        constraints = [
            models.UniqueConstraint(
                fields=("poll", "text"), name="unique_option"
            )
        ]

    def __str__(self):
        return self.text

    @property
    def votes_number(self):
        return self.votes.count()


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    option = models.ForeignKey(
        Option, on_delete=models.CASCADE, related_name="votes"
    )

    def validate_unique_vote(self):
        if Vote.objects.filter(
            user=self.user, option__poll=self.option.poll
        ).exists():
            raise ValidationError("Vote must be unique")

    def save(self, *args, **kwargs):
        self.validate_unique_vote()
        super().save(*args, **kwargs)

ponder_poll/polls/forms.py
from django.forms import ModelForm, inlineformset_factory
from polls.models import Option, Poll, Vote


class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ("text",)


class OptionForm(ModelForm):
    class Meta:
        model = Option
        fields = ("text",)


class VoteForm(ModelForm):
    class Meta:
        model = Vote
        fields = []


PollOptionCreateFormSet = inlineformset_factory(
    Poll, Option, form=OptionForm, extra=10, can_delete=False
)
PollOptionUpdateFormSet = inlineformset_factory(
    Poll, Option, form=OptionForm, extra=10, can_delete_extra=False, max_num=10
)

ponder_poll/polls/views.py
import asyncio

import aiohttp
from asgiref.sync import async_to_sync
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from polls.forms import (
    PollForm,
    PollOptionCreateFormSet,
    PollOptionUpdateFormSet,
    VoteForm,
)
from polls.models import Option, Poll, Vote


class PollCreateView(LoginRequiredMixin, CreateView):
    """
    Create a poll and up to 10 options for it.
    """

    form_class = PollForm
    template_name = "polls/poll-create-edit.html"

    def get_success_url(self):
        return reverse("polls:poll-view", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["formset"] = PollOptionCreateFormSet(self.request.POST)
        else:
            context["formset"] = PollOptionCreateFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if formset.is_valid():
            poll = form.save(commit=False)
            poll.owner = self.request.user
            poll.save()
            self.object = poll
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class PollListView(ListView):
    """
    Return list of polls and some facts from third party API.
    """

    model = Poll
    queryset = Poll.objects.prefetch_related("options", "options__votes").all()
    template_name = "polls/index.html"
    paginate_by = 9

    @staticmethod
    async def _get_fact(session, url):
        async with session.get(url) as response:
            fact = await response.json()
            return fact[0]["fact"]

    async def _get_facts(self, amount):
        actions = []
        async with aiohttp.ClientSession(
            headers={"X-Api-Key": settings.API_NINJAS_KEY}
        ) as session:
            for i in range(amount):
                actions.append(
                    asyncio.ensure_future(
                        self._get_fact(
                            session, "https://api.api-ninjas.com/v1/facts"
                        )
                    )
                )
            facts = await asyncio.gather(*actions)
        return facts

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if not cache.get("facts", None):
            cache.set("facts", async_to_sync(self._get_facts)(3), 60 * 10)
        context["facts"] = cache.get("facts")
        return context


class PollDetailView(LoginRequiredMixin, DetailView):
    """
    Return the poll by the poll id.
    """

    template_name = "polls/poll-view.html"
    queryset = Poll.objects.prefetch_related("options", "options__votes").all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["voted"] = False
        vote = Vote.objects.filter(
            user=self.request.user, option__poll=kwargs["object"]
        )
        if vote:
            context["voted"] = True
            context["chosen_option"] = vote.first().option
        return context


class PollUpdateView(LoginRequiredMixin, UpdateView):
    """
    Update the poll and up to 10 of its options.
    """

    model = Poll
    form_class = PollForm
    template_name = "polls/poll-create-edit.html"

    def get_success_url(self):
        return reverse("polls:poll-view", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["formset"] = PollOptionUpdateFormSet(
                self.request.POST, instance=self.object
            )
        else:
            context["formset"] = PollOptionUpdateFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if formset.is_valid():
            form.save()
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class PollDeleteView(LoginRequiredMixin, DeleteView):
    """
    Delete the poll by the poll id.
    """

    model = Poll
    success_url = reverse_lazy("polls:index")


@login_required
def vote_option(request, pk):
    """
    Create a vote for an option by option id.
    """
    form = VoteForm()
    vote = form.save(commit=False)
    vote.user = request.user
    option = Option.objects.get(pk=pk)
    vote.option = option
    vote.save()
    return redirect(
        reverse_lazy("polls:poll-view", kwargs={"pk": option.poll.id})
    )

ponder_poll/templates/polls/index.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center">
  <h1>Polls</h1>
  <div class="row row-cols-3">
    {% for poll in poll_list %}
    <div class="col g-5">
      <a href="{% url 'polls:poll-view' pk=poll.id %}">
        <div class="py-5 border border-dark rounded">
          <p>{{ poll.text }}</p>
          <p>Total votes: {{ poll.total_votes }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <nav aria-label="Page navigation">
    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}"
        >&laquo;</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">&laquo;</a>
      </li>
      {% endif %}
      {% for i in paginator.page_range %} {% if page_obj.number == i %}
      <li class="page-item"><a class="page-link active">{{ i }}</a></li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
      {% endif %} {% endfor %} {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{page_obj.next_page_number}}" class="page-link"
        >&raquo;</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">&raquo;</a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
  <h1>Interesting facts</h1>
  {% for fact in facts %}
  <p>{{ fact }}</p>
  {% endfor %}
</div>
{% endblock %}

ponder_poll/templates/polls/poll-create-edit.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
  <p>Poll</p>
  {% csrf_token %}
  {{ form.as_p }}
  {{formset.management_form}}
  <p>Options</p>
  {% for option in formset %}
  {{ option.as_p }}
  {% endfor %}
  <input type="submit" value="Submit">
</form>
{% endblock %}

ponder_poll/templates/polls/poll-view.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center">
  <div class="d-flex justify-content-center">
    <p>Poll: {{ object.text }}</p>
    <form action="{% url 'polls:poll-edit' pk=object.id %}" method="get">
      <input type="submit" value="Edit">
    </form>
  </div>
  <p>OPTIONS</p>
  {% for option in object.options.all %}
  <div class="d-flex justify-content-center">
    <p>{{ option.text }}</p>
    {% if voted %}
    <p class="ms-2">votes: {{ option.votes_number}}</p>
    {% if option == chosen_option %}
    <p class="ms-1">Chosen option</p>
    {% endif %}
    {% else %}
    <form action="{% url 'polls:option-vote' pk=option.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Vote">
    </form>
    {% endif %}
  </div>
  {% endfor %}
  <p>Total votes: {{ object.total_votes }}</p>
</div>
{% endblock %}