ponder_poll/polls/urls.py
from django.urls import path

from polls import views
from polls.views import (
    PollCreateView,
    PollDeleteView,
    PollDetailView,
    PollListView,
    PollUpdateView,
)

urlpatterns = [
    path("", PollListView.as_view(), name="index"),
    path("poll/<int:pk>", PollDetailView.as_view(), name="poll-view"),
    path("poll/add", PollCreateView.as_view(), name="poll-add"),
    path("poll/edit/<int:pk>", PollUpdateView.as_view(), name="poll-edit"),
    path("poll/delete/<int:pk>", PollDeleteView.as_view(), name="poll-delete"),
    path("option/<int:pk>/vote", views.vote_option, name="option-vote"),
]

ponder_poll/ponder_poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("", include(("polls.urls", "polls"), namespace="polls")),
]

ponder_poll/users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from users.views import SignUpView

urlpatterns = [
    path("sign-up", SignUpView.as_view(), name="sign-up"),
    path(
        "sign-in",
        LoginView.as_view(template_name="users/sign-in.html"),
        name="sign-in",
    ),
]

ponder_poll/templates/includes/header.html
<div class="container">
  <header class="d-flex justify-content-left py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'polls:index' %}"
                              class="nav-link active" aria-current="page">PonderPoll</a>
      </li>
      <li class="nav-item"><a href="{% url 'users:sign-up' %}" class="nav-link">SignUp</a></li>
      <li class="nav-item"><a href="{% url 'users:sign-in' %}" class="nav-link">SignIn</a></li>
      <li class="nav-item"><a href="{% url 'polls:poll-add' %}" class="nav-link">CreatePoll</a></li>
    </ul>
  </header>
</div>